<?php get_header('Términos y condiciones'); ?>
<div id="legal">
  <h2>Condiciones Generales</h2>
  <p>Las presentes Condiciones Generales constituyen las normas y reglas dispuestas por Mixalo, relativas a todos los servicios y contenidos existentes actualmente o en un futuro dentro del sitio Mixalo.com (el “Sitio”). Dichos servicios y contenidos si bien pueden ser gratuitos, no son de libre utilización, sino que sólo se considerarán lícitos y autorizados cuando lo sean en cumplimiento de las obligaciones impuestas, con los límites y alcances aquí delineados, así como los que surjan de diferentes normativas legales de orden nacional e internacional cuya aplicación corresponda.<p>
  <h3>1. La aceptación por parte de los Usuarios</h3>
  <p>Mixalo se reserva el derecho a exigir que cada usuario, acepte y cumpla los términos aquí expresados como condición previa y necesaria para el acceso, y utilización de los servicios y/o contenidos brindados por el Sitio.</p>
  <p>Cuando un usuario accediere al Sitio y utilizare cualquiera de los servicios y/o contenidos existentes, hará presumir el conocimiento del presente texto y que ha manifestado su plena aceptación con respecto a todas y cada una de las disposiciones que lo integran.</p>
  <h3>2. Capacidad legal de los usuarios</h3>
  <p>Solo podrán acceder y utilizar los servicios y/o contenidos de Mixalo, quienes a tenor de la legislación vigente en su lugar de residencia posean tal capacidad para acceder u obligarse válidamente a los términos y condiciones aquí establecidos.</p>
  <p>Cuando se trate de falta de capacidad por minoría de edad, la responsabilidad en la determinación de los servicios y contenidos a los que acceden los menores de edad corresponde a los mayores a cuyo cargo se encuentren, sin embargo en ningún caso estará permitido el acceso al sitio por parte de menores de 18 años de edad.</p>
  <h3>3. Registración de los Usuarios</h3>
  <p>Al acceder a este sitio y utilizar el contenido de lo mismo, el usuario acepta, sin reserva ni limitación, las condiciones que se expresan a continuación y la legislación vigente además de reconocer que cualquier otro acuerdo entre el usuario y Mixalo queda anulado y sin vigencia ni efecto.</p>
  <p>Mixalo podrá rechazar cualquier solicitud de registración o, cancelar una registración previamente aceptada, sin que tal decisión deba ser justificada, y sin que ello genere derecho alguno en beneficio de los usuarios.</p>
  <h3>4. Libre acceso a los Servicios</h3>
  <p>Los usuarios pueden descargar, visualizar e imprimir información contenida en el presente sitio Web (en adelante, la "Información"), única y exclusivamente para fines personales y no comerciales.</p>
  <h3>5. De los servicios y contenidos en particular</h3>
  <p>Mixalo es un sitio de Internet basado en una herramienta de comunicación, que permite poner en contacto a sus usuarios para que los mismos compartan opiniones, comentarios, y en general cualquier tipo de información que sea de su interés. El objetivo de Mixalo es la creación de un ámbito de comunicación y esparcimiento tan amplio como sea posible, destinado al público de Internet en general.</p>
  <h3>6. Disposiciones comunes</h3>
  <p>a) Todo usuario será exclusivo responsable por los post y comentarios que fije.</p>
  <p>b) La enumeración precedente es al solo efecto enunciativo ya que Mixalo podrá agregar, modificar, suprimir total o parcialmente los servicios y contenidos, sin que para ello se requiera conformidad o notificación previa de ningún tipo. Salvo estipulación en contrario, todo nuevo contenido o ampliación de los existentes se regirá por estas Condiciones Generales.</p>
  <h3>7. Responsabilidades, dirección y control sobre los servicios.</h3>
  <h4>7.1. Facultades reservadas</h4>
  <p>Mixalo se reserva todas las facultades de control y dirección del Sitio, en particular de los servicios, contenidos y comunicaciones habidos dentro del mismo. Podrá en consecuencia Mixalo, introducir todos los cambios y modificaciones que estime convenientes a su solo criterio, podrá agregar, alterar, sustituir o suprimir cualquiera de los servicios o contenidos en todo momento.</p>
  <p>En especial Mixalo se reserva la facultad de controlar, editar, suprimir parcial o totalmente, cualquier post o comentario fijado por un usuario. Dicha facultad reposa en las facultades de dirección que posee Mixalo en cuanto titular del Sitio, y su ejercicio no estará supeditado a justificación o causa alguna, quedando en todos los casos dicho ejercicio reservado a la discreción y voluntad de Mixalo.</p>
  <h4>7.2. Responsabilidades en relación a los servicios prestados:</h4>
  <p>Cada usuario será exclusivo responsable por las manifestaciones que vierta o las acciones que lleve adelante dentro del marco del sitio. Sin embargo cuando Mixalo reciba a través de su mecanismo de recepción de denuncias, la manifestación de una persona, que hubiere sufrido en forma injustificada un menoscabo en cualquiera de sus derechos, tomará en forma inmediata las medidas necesarias para evitar la continuación de la situación perjudicial, y pondrá en conocimiento de las autoridades competentes los acontecimientos del caso.</p>
  <p>Sin perjuicio de estas facultades reservadas, Mixalo en respeto de la privacidad y confidencialidad de las comunicaciones de los usuarios, no ejercerá un control de legalidad directo sobre las manifestaciones y/o acciones llevadas adelante por los usuarios. Consecuentemente no será responsable por el uso contrario a derecho que de los contenidos y servicios, hagan los usuarios, ni garantiza que los datos proporcionados por estos, relativos a su identidad sean veraces y fidedignos.</p>
  <p>Mixalo es una plataforma concebida para la comunicación y difusión de información, la utilización del Sitio realizada por un usuario, que impliquen un desmedro o la lisa y llana violación de derechos de terceros, en especial los relativos a la propiedad intelectual, hará plenamente responsable a ese usuario por los daños que tal conducta irrogare para los terceros y/o Mixalo.</p>
  <p>Mixalo o sus integrantes, NO serán responsables en modo alguno por el contenido de las manifestaciones, opiniones, comentarios, e información volcada en un post o comentario.</p>
  <h4>8.1. USO PROHIBIDO de los servicios o contenidos</h4>
  <p>Aunque Mixalo se esfuerza en lo razonable para incluir en este sitio Web información precisa y actualizada, no ofrece garantía alguna respecto a su contenido, el cual se presenta "tal cual". Mixalo no se responsabiliza de ninguna contingencia relacionada con el uso del presente sitio Web o de su contenido. Concretamente, Mixalo no se responsabiliza de la precisión, integridad, suficiencia, actualidad, oportunidad o el carácter exhaustivo de la información contenida en este sitio. Adicionalmente, Mixalo no se responsabiliza de ningún daño producido a su equipo informático u otros bienes de su propiedad, ni de ningún virus que pueda infectar los mismos, como consecuencia del acceso por parte de los Usuarios del sitio o el uso o exploración del mismo, o el descargo de cualquier materia, datos, texto, imágenes o contenido audiovisual. Mixalo se reserva el derecho de interrumpir o suspender total o parcialmente la funcionalidad del sitio. Mixalo no se responsabiliza de la eventual interrupción o suspensión del presente sitio, sea como consecuencia de las actuaciones u omisiones de cualquier entidad perteneciente a Mixalo, o las de cualquier tercero.</p>
  <h4>8.2. Medidas de control</h4>
  <p>Sin perjuicio de las acciones legales nacidas en cabeza de Mixalo o terceros, cuando el uso de los servicios, llevado adelante por parte de un usuario pueda ser reputado por Mixalo como USO PROHIBIDO, Mixalo tomará las medidas que considere convenientes según su exclusivo criterio, pudiendo suspender o impedir el acceso a los servicios o contenidos a aquellos usuarios incursos en el uso prohibido de los mismos, y sin que para ello deba mediar comunicación previa alguna.</p>
  <h3>9. Aspectos relacionados con la Propiedad Intelectual</h3>
  <h4>9.1. Contenido de terceros</h4>
  <p>En uso de los servicios ofrecidos en el Sitio, el usuario puede tener acceso a contenidos provistos por otros usuarios o terceros. Mixalo realiza sus mejores esfuerzos para controlar el material que le es suministrado, sin embargo, el usuario acepta que eventualmente podrá ser expuesto a contenido de terceros que sea falso, ofensivo, indecente o de otra manera inaceptable. Bajo ninguna circunstancia podrá responsabilizar a Mixalo por tal circunstancia.</p>
  <p>Puesto que Mixalo no ha estudiado ni una parte ni la totalidad del sitios Web vinculadas a este, los usuarios aceptan que Mixalo no se responsabilice del contenido de ningun sitio externo al presente sitio ni de ningún otro sitio vinculado al mismo. Los usuarios acceden al presente sitio y a los sitios externos u otros sitios bajo su propio riesgo y sin la autorización de Mixalo.</p>
  <h4>9.2. Material titularidad de Mixalo</h4>
  <p>El usuario debe conservar y reproducir todos y cada uno de los avisos de titularidad de la propiedad intelectual u otros derechos de la propiedad que constan en la Información que descarga. No obstante, los usuarios no tienen permiso para distribuir, modificar, transmitir, volver a utilizar o colocar de nuevo el contenido del presente sitio Web, incluidos el texto, las imágenes y el contenido audiovisual, para fines públicos o comerciales sin la autorización escrita de Mixalo. Deberán entenderse que todos los derechos sobre el contenido de este sitio Web están reservados, salvo indicación en sentido contrario, y por tanto no se puede utilizar dicho contenido, excepto con arreglo a las presentes Condiciones o con arreglo al texto mismo del contenido, sin la autorización escrita de Mixalo. Mixalo no manifiesta ni garantiza que el uso que haga los usuarios del contenido del presente sitio Web no vulnere los derechos de terceros ajenos a Mixalo.</p>
  <p>Salvo la anterior autorización limitada, no se le otorga ni se le concede a los usuarios ninguna licencia ni derecho con respecto a los derechos de propiedad intelectual pertenecientes a Mixalo o a cualquier otra persona.</p>
  <h3>10. Operatividad del sitio</h3>
  <p>Correspondientemente con el carácter gratuito de los servicios brindados, Mixalo no garantiza la plena operatividad del sitio y el acceso a los servicios y contenidos del mismo. En ningún caso Mixalo responderá por la operatividad, eficacia y seguridad de los servicios y contenidos puestos a disposición de los usuarios.</p>
  <p>Mixalo no garantiza la conservación, integridad ni indemnidad de los post, mensajes o comentarios fijados por los usuarios.</p>
  <h3>11. LINKS hacia Mixalo</h3>
  <p>En ningún caso Mixalo será responsable por los contenidos o manifestaciones existentes en las páginas web desde donde se establezcan los hipervínculos hacia el sitio de Mixalo. El hecho que exista un link entre una página web y el sitio de Mixalo no implica que Mixalo tenga conocimiento de ello, o que Mixalo mantenga relación alguna con los titulares de la página web desde donde se establece el enlace.</p>
  <p>Mixalo se reserva el derecho a solicitar la remoción o eliminación de cualquier enlace desde una página web ajena al Sitio, en cualquier momento, sin expresión de causa, y sin que sea necesario preaviso alguno. El responsable de la página web desde la cual se efectuare el enlace tendrá un plazo de 48hs. contados a partir del pedido de Mixalo para proceder a la remoción o eliminación del mismo.</p>
  <h3>12. LINKS desde Mixalo</h3>
  <p>Puesto que Mixalo no ejerce ningún control sobre los sitios vinculados al presente sitio Web, ni autoriza los mismos, y puesto que Mixalo no ha estudiado ni una parte ni la totalidad de los sitios Web vinculados a la presente, el usuario acepta que Mixalo no se responsabilice del contenido de ninguna sitio externa al presente sitio ni de ningún otro sitio vinculado al mismo. Los usuarios acceden al presente sitio y a los sitios externas u otros sitios bajo su propio riesgo y sin la autorización de Mixalo.</p>
  <p>Aunque Mixalo podrá ocasionalmente estudiar o seguir la marcha de los debates, charlas, transmisiones, anuncios y otros elementos del presente sitio Web, Mixalo no tiene la obligación de efectuar dicho estudio o seguimiento, y no se responsabiliza del contenido de tales elementos, ni de ningún error, difamación, calumnia, injuria, omisión, falsedad, obscenidad, pornografía, blasfemia o imprecisión en la información contenida en dichos elementos del presente sitio Web. Se prohíbe la colocación o la transmisión de toda materia ilícita, amenazadora, calumniosa, difamatoria, obscena, escandalosa, pornográfica o blasfema, o cualquier materia que pudiera constituir o inducir a conductas que podrían tipificarse como delito, ocasionar responsabilidad civil, o vulnerar de otra forma cualquier ley. Mixalo colaborará plenamente con cualquier autoridad encargada de hacer cumplir la ley o cualquier requerimiento judicial que inste a Mixalo a revelar la identidad de cualquier persona que coloque tal información o materia.</p>
  <p>Mixalo podrá modificar en cualquier momento las presentes Condiciones. Dicha modificación es vinculante para todos los usuarios y por tanto le recomendamos que visite este sitio periódicamente, para saber las Condiciones vigentes que le afectan.</p>
</div>
<?php get_footer(); ?>